#include "zari/app.hpp"
#include "zari/search.hpp"
#include <algorithm>
#include <csignal>
#include <fstream>
#include <sys/wait.h>
#include <unistd.h>
namespace zari {
std::optional<Cli>parse_cli(int argc,char**argv,std::string&e){Cli c;bool path=false;for(int i=1;i<argc;++i){std::string a=argv[i];if(a=="--help"||a=="-h")c.help=true;else if(a=="--version"||a=="-V")c.version=true;else if(a=="--debug")c.debug=true;else if(a=="--config"||a=="--theme"){if(++i>=argc){e=a+" requires a value";return{};}if(a=="--config")c.config=argv[i];else c.theme=argv[i];}else if(!a.empty()&&a[0]=='-'){e="unknown option: "+a;return{};}else if(path){e="only one starting path may be supplied";return{};}else{c.start=a;path=true;}}return c;}
namespace {bool launch(const std::string&program,const fs::path&p,std::string&e){pid_t pid=fork();if(pid<0){e="fork failed";return false;}if(pid==0){execlp(program.c_str(),program.c_str(),p.c_str(),static_cast<char*>(nullptr));_exit(127);}int status=0;if(waitpid(pid,&status,0)<0){e="wait failed";return false;}if(!WIFEXITED(status)||WEXITSTATUS(status)!=0){e=program+" exited unsuccessfully";return false;}return true;} }
App::App(Cli c):cli_(std::move(c)){auto cp=cli_.config.value_or(config_directory()/"zari.toml");auto loaded=load_config(cp);config_=loaded.value;if(cli_.theme)config_.theme_name=*cli_.theme;keymap_=Keymap::defaults();keymap_.overlay(config_directory()/"keymap.toml",loaded.warnings);theme_=builtin_theme(config_.theme_name);overlay_theme_file(theme_,config_directory()/"theme.toml",loaded.warnings);if(!loaded.warnings.empty())message_=loaded.warnings.front();manager_=std::make_unique<Manager>(cli_.start,config_);}
void App::prompt(std::string label,std::function<void(const std::string&)>done){Ui u(theme_);echo();curs_set(1);timeout(-1);u.draw(*manager_,Mode::input,message_,label,keymap_);int h,w;getmaxyx(stdscr,h,w);(void)w;char buf[4096]{};move(h-1,static_cast<int>(label.size()+2));getnstr(buf,sizeof(buf)-1);noecho();curs_set(0);timeout(100);done(buf);}
void App::reload(){auto loaded=load_config(cli_.config.value_or(config_directory()/"zari.toml"));if(!loaded.valid){message_="reload rejected: "+(loaded.warnings.empty()?"invalid config":loaded.warnings.front());return;}auto km=Keymap::defaults();if(!km.overlay(config_directory()/"keymap.toml",loaded.warnings)){message_="reload rejected: keymap unreadable";return;}auto th=builtin_theme(cli_.theme.value_or(loaded.value.theme_name));if(!overlay_theme_file(th,config_directory()/"theme.toml",loaded.warnings)){message_="reload rejected: theme unreadable";return;}config_=loaded.value;manager_->config=config_;keymap_=std::move(km);theme_=std::move(th);manager_->refresh();message_=loaded.warnings.empty()?"configuration reloaded":loaded.warnings.front();}
void App::execute(const Binding&b){auto&t=manager_->tab();auto current=[&](){return t.current();};std::string err;
 if(b.action=="down")t.move(1);else if(b.action=="up")t.move(-1);else if(b.action=="half_down")t.move(10);else if(b.action=="half_up")t.move(-10);else if(b.action=="top")t.top();else if(b.action=="bottom")t.bottom();else if(b.action=="parent")t.navigate(t.directory.parent_path(),config_.manager,err);else if(b.action=="home")t.navigate(home_directory(),config_.manager,err);else if(b.action=="back")t.back(config_.manager,err);else if(b.action=="forward")t.forward(config_.manager,err);else if(b.action=="cd")t.navigate(fs::path(b.arg).is_absolute()?fs::path(b.arg):home_directory()/fs::path(b.arg).relative_path(),config_.manager,err);else if(b.action=="open"&&current()){if(current()->kind==FileKind::directory)t.navigate(current()->path,config_.manager,err);else launch(config_.opener,current()->path,err);}else if(b.action=="select"&&current()){auto p=current()->path;if(!t.selected.erase(p))t.selected.insert(p);t.move(1);mode_=t.selected.empty()?Mode::normal:Mode::select;}else if(b.action=="visual"){mode_=mode_==Mode::visual?Mode::normal:Mode::visual;}else if(b.action=="copy"||b.action=="cut"){manager_->set_clipboard(b.action=="copy"?ClipMode::copy:ClipMode::cut);message_=std::to_string(manager_->clipboard.size())+" item(s) staged";}else if(b.action=="paste"){manager_->paste(err);}else if((b.action=="trash"||b.action=="delete")&&current()){auto targets=manager_->targets();prompt((b.action=="delete"?"Permanently delete":"Trash")+std::string(" ")+std::to_string(targets.size())+" item(s)? [y/N] ",[&,targets,action=b.action](const std::string&v){if(v!="y"&&v!="Y"){message_="cancelled";return;}for(auto&p:targets){std::string x;bool ok=action=="delete"?remove_path(p,x):trash_path(p,x);if(!ok){message_=x;break;}}manager_->clear_selection();manager_->refresh();});}
 else if(b.action=="rename"&&current()){auto old=current()->path;prompt("Rename to:",[&,old](const std::string&v){if(v.empty()||fs::path(v).filename()!=v){message_="invalid name";return;}std::error_code ec;fs::rename(old,old.parent_path()/v,ec);message_=ec?ec.message():"renamed";manager_->refresh();});}else if(b.action=="create_file"||b.action=="create_directory"){prompt(b.action=="create_file"?"New file:":"New directory:",[&,action=b.action](const std::string&v){if(v.empty()||fs::path(v).filename()!=v){message_="invalid name";return;}std::error_code ec;if(action=="create_directory")fs::create_directory(t.directory/v,ec);else{std::ofstream f(t.directory/v);if(!f)message_="cannot create file";}if(ec)message_=ec.message();manager_->refresh();});}else if(b.action=="hidden"){config_.manager.show_hidden=!config_.manager.show_hidden;manager_->config=config_;manager_->refresh();}else if(b.action=="new_tab")manager_->new_tab();else if(b.action=="close_tab"){if(!manager_->close_tab())message_="cannot close the last tab";}else if(b.action=="previous_tab")manager_->switch_tab(-1);else if(b.action=="next_tab")manager_->switch_tab(1);else if(b.action=="tab"&&!b.arg.empty())manager_->direct_tab(static_cast<std::size_t>(b.arg[0]-'1'));else if(b.action=="find"){mode_=Mode::search;input_.clear();}else if(b.action=="filename_search"){prompt("Recursive filename search:",[&](const std::string&q){auto r=filename_search(t.directory,q,500,err);message_=err.empty()?std::to_string(r.size())+" matches (first: "+(r.empty()?"none":r.front().string())+")":err;});}else if(b.action=="content_search")message_="content search: use rg in this version";else if(b.action=="help")mode_=mode_==Mode::help?Mode::normal:Mode::help;else if(b.action=="reload")reload();else if(b.action=="quit"){if(manager_->tasks.active()&&config_.confirm.quit_with_tasks)message_="tasks active; press q again to cancel and quit";else running_=false;}
 if(!err.empty())message_=err;}
int App::run(){Terminal terminal;Ui ui(theme_);while(running_){ui.apply_theme(theme_);ui.draw(*manager_,mode_,message_,mode_==Mode::search?"/"+input_:"",keymap_);int ch=getch();if(ch==ERR)continue;if(ch==KEY_RESIZE)continue;auto key=key_name(ch);if(mode_==Mode::help&&(key=="Esc"||key=="?")){mode_=Mode::normal;continue;}if(mode_==Mode::search){if(key=="Esc"||key=="\n"){mode_=Mode::normal;input_.clear();continue;}if(key=="Backspace"){if(!input_.empty())input_.pop_back();}else if(ch>=32&&ch<127)input_+=static_cast<char>(ch);if(!input_.empty()){auto it=std::find_if(manager_->tab().entries.begin(),manager_->tab().entries.end(),[&](const auto&e){return fuzzy_match(e.name,input_,config_.manager.case_sensitive);});if(it!=manager_->tab().entries.end())manager_->tab().cursor=it-manager_->tab().entries.begin();}continue;}if(key=="Up")key="k";else if(key=="Down")key="j";else if(key=="Left")key="h";else if(key=="Right")key="l";sequence_.push_back(key);if(auto b=keymap_.exact(sequence_)){execute(*b);sequence_.clear();}else if(!keymap_.is_prefix(sequence_)){sequence_.clear();message_="unbound key";}if(mode_==Mode::visual){if(auto*c=manager_->tab().current())manager_->tab().selected.insert(c->path);}}
 return 0;}
}
