#include "zari/filesystem.hpp"
#include <algorithm>
#include <cctype>
#include <fstream>
#include <iomanip>
#include <random>
#include <sstream>
#include <sys/stat.h>

namespace zari {
namespace { FileKind kind(const fs::directory_entry& d,std::error_code& ec){auto s=d.symlink_status(ec);if(ec)return FileKind::other;if(fs::is_symlink(s)){auto target=fs::status(d.path(),ec);(void)target;return ec?FileKind::broken_symlink:FileKind::symlink;}if(fs::is_directory(s))return FileKind::directory;if(fs::is_socket(s))return FileKind::socket;if(fs::is_fifo(s))return FileKind::fifo;if(fs::is_block_file(s))return FileKind::block;if(fs::is_character_file(s))return FileKind::character;if(fs::is_regular_file(s)){auto p=s.permissions();if((p&fs::perms::owner_exec)!=fs::perms::none||(p&fs::perms::group_exec)!=fs::perms::none||(p&fs::perms::others_exec)!=fs::perms::none)return FileKind::executable;return FileKind::regular;}return FileKind::other;} }
std::string natural_key(std::string_view s,bool cs){std::string o;for(std::size_t i=0;i<s.size();){unsigned char c=s[i];if(std::isdigit(c)){std::size_t j=i;while(j<s.size()&&std::isdigit(static_cast<unsigned char>(s[j])))++j;auto n=s.substr(i,j-i);auto z=n.find_first_not_of('0');auto core=z==std::string_view::npos?std::string_view("0"):n.substr(z);o.push_back('\1');o+=std::string(12-core.size(),'0');o+=core;o.push_back('\1');i=j;}else{o.push_back(cs?static_cast<char>(c):static_cast<char>(std::tolower(c)));++i;}}return o;}
DirectoryResult list_directory(const fs::path& p,const ManagerConfig& c){DirectoryResult r;std::error_code ec;fs::directory_iterator it(p,fs::directory_options::skip_permission_denied,ec);if(ec){r.error=ec.message();return r;}for(const auto& d:it){FileEntry e;e.path=d.path();e.name=d.path().filename().string();e.hidden=!e.name.empty()&&e.name[0]=='.';if(e.hidden&&!c.show_hidden)continue;e.kind=kind(d,ec);ec.clear();e.permissions=d.symlink_status(ec).permissions();ec.clear();e.modified=d.last_write_time(ec);ec.clear();if(e.kind==FileKind::regular||e.kind==FileKind::executable)e.size=d.file_size(ec);ec.clear();if(e.kind==FileKind::symlink){e.symlink_target=fs::read_symlink(e.path,ec);ec.clear();}r.entries.push_back(std::move(e));}
 if(c.sort_by==SortBy::random){std::mt19937 g{std::random_device{}()};std::shuffle(r.entries.begin(),r.entries.end(),g);}else if(c.sort_by!=SortBy::none)std::stable_sort(r.entries.begin(),r.entries.end(),[&](const auto&a,const auto&b){if(c.directories_first){bool ad=a.kind==FileKind::directory,bd=b.kind==FileKind::directory;if(ad!=bd)return ad;}bool less=false;switch(c.sort_by){case SortBy::size:less=a.size<b.size;break;case SortBy::modified:case SortBy::created:less=a.modified<b.modified;break;case SortBy::extension:less=natural_key(a.path.extension().string(),c.case_sensitive)<natural_key(b.path.extension().string(),c.case_sensitive);break;default:less=natural_key(a.name,c.case_sensitive)<natural_key(b.name,c.case_sensitive);break;}return c.sort_reverse?!less&&a.name!=b.name:less;});return r;}
std::string human_size(std::uintmax_t n){const char*u[]={"B","K","M","G","T"};double v=static_cast<double>(n);int i=0;while(v>=1024&&i<4){v/=1024;++i;}std::ostringstream s;s<<std::fixed<<std::setprecision(i?1:0)<<v<<u[i];return s.str();}
std::string permission_string(fs::perms p){std::string s;for(auto bit:{fs::perms::owner_read,fs::perms::owner_write,fs::perms::owner_exec,fs::perms::group_read,fs::perms::group_write,fs::perms::group_exec,fs::perms::others_read,fs::perms::others_write,fs::perms::others_exec})s+=((p&bit)!=fs::perms::none?(bit==fs::perms::owner_read||bit==fs::perms::group_read||bit==fs::perms::others_read?'r':bit==fs::perms::owner_write||bit==fs::perms::group_write||bit==fs::perms::others_write?'w':'x'):'-');return s;}
fs::path collision_free(const fs::path& p){if(!fs::exists(p))return p;for(int i=1;;++i){auto q=p.parent_path()/(p.stem().string()+" ("+std::to_string(i)+")"+p.extension().string());if(!fs::exists(q))return q;}}
bool copy_path(const fs::path& a,const fs::path& b,std::string& error){std::error_code ec;if(fs::is_symlink(fs::symlink_status(a,ec))){fs::copy_symlink(a,b,ec);}else if(fs::is_directory(a,ec)){fs::copy(a,b,fs::copy_options::recursive,ec);}else fs::copy_file(a,b,fs::copy_options::none,ec);if(ec){error=ec.message();return false;}return true;}
bool move_path(const fs::path&a,const fs::path&b,std::string&error){std::error_code ec;fs::rename(a,b,ec);if(!ec)return true;if(!copy_path(a,b,error))return false;return remove_path(a,error);}
bool remove_path(const fs::path&p,std::string&error){std::error_code ec;fs::remove_all(p,ec);if(ec){error=ec.message();return false;}return true;}
bool trash_path(const fs::path&p,std::string&error){auto root=home_directory()/".local/share/Trash";std::error_code ec;fs::create_directories(root/"files",ec);fs::create_directories(root/"info",ec);if(ec){error=ec.message();return false;}auto dst=collision_free(root/"files"/p.filename());if(!move_path(p,dst,error))return false;std::ofstream info(root/"info"/(dst.filename().string()+".trashinfo"));if(!info){error="cannot write trash metadata";return false;}auto original=fs::absolute(p).string();std::string encoded;for(unsigned char c:original){if(std::isalnum(c)||std::string("/-_.~").find(c)!=std::string::npos)encoded+=static_cast<char>(c);else{char b[4];std::snprintf(b,sizeof b,"%%%02X",c);encoded+=b;}}auto now=std::time(nullptr);std::tm tm{};localtime_r(&now,&tm);info<<"[Trash Info]\nPath="<<encoded<<"\nDeletionDate="<<std::put_time(&tm,"%Y-%m-%dT%H:%M:%S")<<"\n";return true;}
}
