#include "zari/keymap.hpp"
#include <algorithm>
#include <cctype>
#include <fstream>
#include <ncurses.h>

namespace zari {
namespace { std::string trim(std::string s){auto p=s.find_first_not_of(" \t");if(p==std::string::npos)return{};return s.substr(p,s.find_last_not_of(" \t")-p+1);} std::string val(std::string s){s=trim(s);if(s.size()>1&&s.front()=='"'&&s.back()=='"')return s.substr(1,s.size()-2);return s;} std::vector<std::string> array(std::string s){std::vector<std::string> r;if(s.size()<2)return r;s=s.substr(1,s.size()-2);bool q=false;std::string x;for(char c:s){if(c=='"')q=!q;else if(c==','&&!q){r.push_back(val(x));x.clear();}else x+=c;}if(!trim(x).empty())r.push_back(val(x));return r;} }
Keymap Keymap::defaults(){Keymap k;auto add=[&](std::string keys,std::string action,std::string desc,std::string arg=""){Binding b;for(char c:keys)b.keys.push_back(std::string(1,c));b.action=std::move(action);b.description=std::move(desc);b.arg=std::move(arg);k.bindings_.push_back(std::move(b));};
 add("j","down","Move down");add("k","up","Move up");add("h","parent","Parent directory");add("l","open","Enter/open");add("\n","open","Enter/open");add("gg","top","Jump to top");add("G","bottom","Jump to bottom");add(" ","select","Toggle selection");add("v","visual","Visual selection");add("y","copy","Copy selected");add("x","cut","Cut selected");add("p","paste","Paste");add("cp","copy_paths","Copy selected paths to system clipboard");add("d","trash","Move to trash");add("D","delete","Delete permanently");add("r","rename","Rename");add("a","create_file","Create file");add("A","create_directory","Create directory");add(".","hidden","Toggle hidden");add("/","find","Incremental find");add("f","filename_search","Recursive filename search");add("S","content_search","Content search");add("z","subtree","Choose subtree with fzf");add("Z","zoxide","Choose history with zoxide and fzf");add("o","open_with","Open with");add("q","quit","Quit");add("?","help","Help");add("tt","new_tab","New tab");add("[","previous_tab","Previous tab");add("]","next_tab","Next tab");add("R","reload","Reload configuration");add("b","back","Back history");add("B","forward","Forward history");add("~","home","Home directory");add("/","find","Find");add("\025","half_up","Half page up");add("\004","half_down","Half page down");add("\027","close_tab","Close tab");for(char c='1';c<='9';++c)add(std::string(1,c),"tab","Switch tab",std::string(1,c));return k;}
bool Keymap::overlay(const fs::path&p,std::vector<std::string>&w){std::ifstream f(p);if(!f)return !fs::exists(p);std::string line;Binding cur;bool active=false;int no=0;auto commit=[&]{if(active&&!cur.keys.empty()&&!cur.action.empty()){bindings_.erase(std::remove_if(bindings_.begin(),bindings_.end(),[&](const Binding&b){return b.keys==cur.keys;}),bindings_.end());bindings_.push_back(cur);}cur={};};while(std::getline(f,line)){++no;auto hash=line.find('#');if(hash!=std::string::npos)line.resize(hash);line=trim(line);if(line.empty())continue;if(line=="[[manager.bind]]"){commit();active=true;continue;}auto eq=line.find('=');if(eq==std::string::npos){w.push_back("keymap line "+std::to_string(no)+": expected key = value");continue;}auto k=trim(line.substr(0,eq)),v=line.substr(eq+1);if(k=="keys")cur.keys=array(trim(v));else if(k=="action")cur.action=val(v);else if(k=="arg")cur.arg=val(v);else if(k=="description")cur.description=val(v);}commit();return true;}
std::optional<Binding> Keymap::exact(const std::vector<std::string>&s)const{for(const auto&b:bindings_)if(b.keys==s)return b;return{};}bool Keymap::is_prefix(const std::vector<std::string>&s)const{for(const auto&b:bindings_)if(b.keys.size()>s.size()&&std::equal(s.begin(),s.end(),b.keys.begin()))return true;return false;}
std::string key_name(int c){if(c==KEY_UP)return "Up";if(c==KEY_DOWN)return "Down";if(c==KEY_LEFT)return "Left";if(c==KEY_RIGHT)return "Right";if(c==KEY_ENTER||c=='\r'||c=='\n')return "\n";if(c==27)return "Esc";if(c==KEY_BACKSPACE||c==127)return "Backspace";if(c>=1&&c<=26)return std::string(1,static_cast<char>(c));if(c>=0&&c<256)return std::string(1,static_cast<char>(c));return "Key"+std::to_string(c);}
}
