#include "zari/theme.hpp"
#include <algorithm>
#include <cctype>
#include <fstream>
#include <sstream>
namespace zari {
namespace {Style empty;std::string trim(std::string s){auto p=s.find_first_not_of(" \t");if(p==std::string::npos)return{};return s.substr(p,s.find_last_not_of(" \t")-p+1);}std::map<std::string,Color>named={{"black",{0,0,0,0}},{"red",{205,49,49,1}},{"green",{13,188,121,2}},{"yellow",{229,229,16,3}},{"blue",{36,114,200,4}},{"magenta",{188,63,188,5}},{"cyan",{17,168,205,6}},{"white",{229,229,229,7}}};Style s(std::string fg,std::string bg="",bool bold=false){Style x;x.fg=parse_color(fg);if(!bg.empty())x.bg=parse_color(bg);x.bold=bold;return x;}void set_base(Theme&t,const std::map<std::string,std::string>&p){for(auto[k,v]:p)t.styles[k]=s(v);t.styles["selected"]=s(p.at("background"),p.at("accent"),true);t.styles["cursor"]=t.styles["selected"];t.styles["active_tab"]=t.styles["selected"];t.styles["inactive_tab"]=s(p.at("muted"));t.styles["error"]=s(p.at("red"),"",true);t.styles["warning"]=s(p.at("yellow"));t.styles["success"]=s(p.at("green"));t.styles["info"]=s(p.at("accent"));t.styles["border"]=s(p.at("muted"));t.styles["directory"]=s(p.at("blue"),"",true);t.styles["executable"]=s(p.at("green"));t.styles["symlink"]=s(p.at("cyan"));t.styles["broken_symlink"]=s(p.at("red"));t.styles["hidden_file"]=s(p.at("muted"));t.styles["marked"]=s(p.at("yellow"));t.styles["copied"]=s(p.at("green"));t.styles["cut"]=s(p.at("red"));}}
const Style&Theme::get(const std::string&k)const{auto i=styles.find(k);return i==styles.end()?empty:i->second;}
std::optional<Color>parse_color(const std::string&raw){auto v=raw;if(v.size()>=2&&v.front()=='"'&&v.back()=='"')v=v.substr(1,v.size()-2);if(v.size()==7&&v[0]=='#'){Color c;auto cv=[&](int i){return std::stoi(v.substr(i,2),nullptr,16);};try{c.r=cv(1);c.g=cv(3);c.b=cv(5);c.ansi=-1;return c;}catch(...){return{};}}std::transform(v.begin(),v.end(),v.begin(),[](unsigned char c){return std::tolower(c);});auto i=named.find(v);return i==named.end()?std::nullopt:std::optional<Color>(i->second);}
Theme builtin_theme(const std::string&n){Theme t;t.name=n;std::map<std::string,std::string>p;if(n=="catppuccin-mocha")p={{"background","#1e1e2e"},{"foreground","#cdd6f4"},{"accent","#cba6f7"},{"muted","#6c7086"},{"blue","#89b4fa"},{"green","#a6e3a1"},{"red","#f38ba8"},{"yellow","#f9e2af"},{"cyan","#94e2d5"}};else if(n=="gruvbox-dark")p={{"background","#282828"},{"foreground","#ebdbb2"},{"accent","#d79921"},{"muted","#928374"},{"blue","#83a598"},{"green","#b8bb26"},{"red","#fb4934"},{"yellow","#fabd2f"},{"cyan","#8ec07c"}};else if(n=="dracula")p={{"background","#282a36"},{"foreground","#f8f8f2"},{"accent","#bd93f9"},{"muted","#6272a4"},{"blue","#8be9fd"},{"green","#50fa7b"},{"red","#ff5555"},{"yellow","#f1fa8c"},{"cyan","#8be9fd"}};else if(n=="nord")p={{"background","#2e3440"},{"foreground","#d8dee9"},{"accent","#88c0d0"},{"muted","#4c566a"},{"blue","#81a1c1"},{"green","#a3be8c"},{"red","#bf616a"},{"yellow","#ebcb8b"},{"cyan","#8fbcbb"}};else if(n=="tokyo-night")p={{"background","#1a1b26"},{"foreground","#c0caf5"},{"accent","#bb9af7"},{"muted","#565f89"},{"blue","#7aa2f7"},{"green","#9ece6a"},{"red","#f7768e"},{"yellow","#e0af68"},{"cyan","#7dcfff"}};else{t.name="default";p={{"background","black"},{"foreground","white"},{"accent","blue"},{"muted","cyan"},{"blue","blue"},{"green","green"},{"red","red"},{"yellow","yellow"},{"cyan","cyan"}};}set_base(t,p);t.styles["background"]=s(p["foreground"],p["background"]);t.styles["foreground"]=s(p["foreground"],p["background"]);t.styles["file"]=s(p["foreground"]);t.styles["status_bar"]=s(p["foreground"],p["background"],true);t.styles["header"]=t.styles["status_bar"];t.styles["preview"]=t.styles["file"];return t;}
bool overlay_theme_file(Theme&t,const fs::path&p,std::vector<std::string>&w){std::ifstream f(p);if(!f)return !fs::exists(p);std::string section,line;int no=0;while(std::getline(f,line)){++no;auto hash=line.find('#');if(hash!=std::string::npos&&!(hash>0&&line[hash-1]=='"'))line.resize(hash);line=trim(line);if(line.empty())continue;if(line.front()=='['&&line.back()==']'){section=line.substr(1,line.size()-2);continue;}auto eq=line.find('=');if(eq==std::string::npos)continue;auto key=trim(line.substr(0,eq)),v=trim(line.substr(eq+1));if(v.front()!='{'||v.back()!='}'){w.push_back("theme line "+std::to_string(no)+": style must be inline table");continue;}Style st;std::stringstream ss(v.substr(1,v.size()-2));std::string part;while(std::getline(ss,part,',')){auto e=part.find('=');if(e==std::string::npos)continue;auto k=trim(part.substr(0,e)),x=trim(part.substr(e+1));if(k=="fg")st.fg=parse_color(x);else if(k=="bg")st.bg=parse_color(x);else if(k=="bold")st.bold=x=="true";else if(k=="italic")st.italic=x=="true";else if(k=="underline")st.underline=x=="true";else if(k=="dim")st.dim=x=="true";}std::string canonical=key;if(section=="tabs")canonical=key=="active"?"active_tab":"inactive_tab";else if(section=="status")canonical=key=="normal"?"status_bar":key;t.styles[canonical]=st;}return true;}
}
