#include "zari/ui.hpp"
#include <algorithm>
#include <clocale>
#include <sstream>
#undef border
namespace zari {
std::string mode_name(Mode m){switch(m){case Mode::normal:return"NORMAL";case Mode::select:return"SELECT";case Mode::visual:return"VISUAL";case Mode::search:return"SEARCH";case Mode::input:return"INPUT";case Mode::help:return"HELP";}return"";}
Terminal::Terminal(){std::setlocale(LC_ALL,"");initscr();raw();noecho();keypad(stdscr,TRUE);curs_set(0);set_escdelay(25);timeout(100);start_color();use_default_colors();}Terminal::~Terminal(){endwin();}
Ui::Ui(Theme t):theme_(std::move(t)){apply_theme(theme_);}void Ui::apply_theme(Theme t){theme_=std::move(t);if(!has_colors())return;auto idx=[](const std::optional<Color>&c,int fallback){if(!c)return fallback;if(c->ansi>=0)return c->ansi;if(COLORS>=256){int r=c->r*5/255,g=c->g*5/255,b=c->b*5/255;return 16+36*r+6*g+b;}return fallback;};std::vector<std::string>keys={"file","directory","executable","symlink","broken_symlink","hidden_file","selected","marked","border","header","status_bar","active_tab","inactive_tab","preview","error","warning","success","info"};int pair=1;for(auto&k:keys){auto&s=theme_.get(k);init_pair(pair++,idx(s.fg,COLOR_WHITE),idx(s.bg,-1));}}
void Ui::text(int y,int x,int width,std::string_view s,int attr)const{if(y<0||x<0||width<=0)return;attron(attr);mvaddnstr(y,x,s.data(),std::min<int>(width,s.size()));attroff(attr);}
void Ui::draw(const Manager&m,Mode mode,const std::string&msg,const std::string&input,const Keymap&keys){erase();int h,w;getmaxyx(stdscr,h,w);if(h<5||w<30){text(0,0,w,"Terminal too small",A_BOLD);refresh();return;}int top=0;if(m.config.ui.show_tabs){std::string tabs;for(std::size_t i=0;i<m.tabs.size();++i)tabs+=(i==m.active?"[":" ")+std::to_string(i+1)+":"+m.tabs[i].directory.filename().string()+(i==m.active?"] ":"  ");text(0,0,w,tabs,A_BOLD);top=1;}text(top,0,w,m.tab().directory.string(),A_BOLD);++top;int bottom=m.config.ui.show_status_bar?h-1:h;int body=bottom-top;auto ratio=m.config.manager.layout;int total=ratio[0]+ratio[1]+(m.config.preview.enabled?ratio[2]:0);int pw=total? w*ratio[0]/total:0,cw=total?w*ratio[1]/total:w,vw=w-pw-cw;if(ratio[0]==0)pw=0;if(ratio[2]==0||!m.config.preview.enabled){cw+=vw;vw=0;}auto border=[&](int x){if(x>0&&x<w)for(int y=top;y<bottom;++y)mvaddch(y,x,ACS_VLINE);};border(pw);border(pw+cw);
 auto draw_list=[&](const std::vector<FileEntry>&es,std::size_t cursor,int x,int width,bool active){if(width<=1)return;int row=0;std::size_t start=cursor>=static_cast<std::size_t>(body)?cursor-body+1:0;for(std::size_t i=start;i<es.size()&&row<body;++i,++row){auto&e=es[i];std::string icon;if(m.config.ui.show_file_icons){if(m.config.ui.nerd_fonts)icon=e.kind==FileKind::directory?" ":e.kind==FileKind::symlink?" ":e.kind==FileKind::executable?" ":" ";else icon=e.kind==FileKind::directory?"d ":e.kind==FileKind::symlink?"@ ":e.kind==FileKind::executable?"* ":"  ";}std::string line=icon+e.name;if(m.config.ui.show_size&&(e.kind==FileKind::regular||e.kind==FileKind::executable)){auto z=human_size(e.size);if(static_cast<int>(line.size()+z.size()+1)<width)line+=std::string(width-1-line.size()-z.size(),' ')+z;}int a=(active&&i==cursor)?A_REVERSE:0;if(active&&m.tab().selected.contains(e.path))a|=A_BOLD;text(top+row,x+1,width-2,line,a);}};
 std::vector<FileEntry>parent;if(pw){auto p=list_directory(m.tab().directory.parent_path(),m.config.manager);parent=std::move(p.entries);std::size_t pc=0;for(std::size_t i=0;i<parent.size();++i)if(parent[i].path==m.tab().directory)pc=i;draw_list(parent,pc,0,pw,false);}draw_list(m.tab().entries,m.tab().cursor,pw,cw,true);
 if(vw>1)if(auto*e=m.tab().current()){auto p=make_preview(*e,m.config.preview,vw-2,body-1);text(top,pw+cw+1,vw-2,p.title,A_BOLD);for(std::size_t i=0;i<p.lines.size()&&static_cast<int>(i)<body-1;++i)text(top+1+i,pw+cw+1,vw-2,p.lines[i]);}
 if(mode==Mode::help){int hh=std::min(h-4,24),ww=std::min(w-4,72),y=(h-hh)/2,x=(w-ww)/2;for(int r=0;r<hh;++r){move(y+r,x);for(int c=0;c<ww;++c)addch(' '|A_REVERSE);}text(y,x+2,ww-4,"Zari keybindings — press ? or Esc to close",A_REVERSE|A_BOLD);int r=1;for(const auto&b:keys.bindings()){if(r>=hh)break;std::string ks;for(auto&k:b.keys)ks+=(k=="\n"?"Enter":k)+" ";text(y+r++,x+2,ww-4,ks+"  "+b.description,A_REVERSE);}}
 if(m.config.ui.show_status_bar){std::ostringstream s;s<<mode_name(mode)<<"  "<<m.tab().selected.size()<<" selected  "<<m.tab().entries.size()<<" items";if(!msg.empty())s<<"  | "<<msg;if(!input.empty())s<<"  "<<input;text(h-1,0,w,s.str(),A_REVERSE);}refresh();}
}
